---
resource_types:
- name: artifactory-resource
  type: docker-image
  source: {repository: springio/artifactory-resource, tag: 0.0.6}



resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/sabbyanandan/xfmr.git
    branch: master
    ignore_paths:
    - ci/docker-image/*

- name: 1-1-app-latest-artifactory-upload
  type: artifactory-resource
  check_every: 1m
  source:
    uri: ((artifactory_uri))
    username: ((artifactory_username))
    password: ((artifactory_password))
    build_name: my-app-build

- name: 1-2-app-latest-image-push
  type: docker-image
  source:
    repository: sabby/xfmr
    username: ((docker_username))
    password: ((docker_password))



# Docker Images
- name: get-alpine-latest
  type: docker-image
  source:
    repository: alpine
    tag:        latest
- name: build-blanket-docker-image-on-new-commits
  type: git
  source:
    uri:    https://github.com/sabbyanandan/xfmr.git
    branch: master
    paths:
    - ci/docker-image/*
- name: build-blanket-docker-image-for-app-ops
  type: docker-image
  source:
    repository: sabby/blanket-docker-image-for-app-ops
    username:   ((docker_username))
    password:   ((docker_password))



jobs:
- name: 1-build-app-artifact
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: git-repo/ci/latest/deploy.yml
  - aggregate:
    - put: 1-1-app-latest-artifactory-upload
      params:
        repo: libs-snapshot-local
        build_number: "${BUILD_ID}"
        folder: distribution-repository
        build_uri: "${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
        disable_checksum_uploads: true
    - put: 1-2-app-latest-image-push
      params:
        build: docker-image
        tag: docker-image/projectVersion

- name: 2-register-app-artifact
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-repo
      passed:
      - 1-build-app-artifact
    - get: distribution-repository
      resource: 1-1-app-latest-artifactory-upload
      trigger: true
      passed:
      - 1-build-app-artifact
      params:
        generate_maven_metadata: true
    - get: docker-image
      resource: 1-2-app-latest-image-push
      trigger: true
      passed:
      - 1-build-app-artifact
  - aggregate:
    - task: 2-1-register-docker
      file: git-repo/ci/latest/register-docker-image.yml
    - task: 2-2-register-maven
      file: git-repo/ci/latest/register-maven-app.yml

- name: blanket-docker-image
  public: true
  plan:
  - aggregate:
    - get: build-blanket-docker-image-on-new-commits
      trigger: true
    - get: get-alpine-latest
      trigger: true
  - put: build-blanket-docker-image-for-app-ops
    params:
      build: build-blanket-docker-image-on-new-commits/ci/docker-image